projet_restaurant/accueil/urls.py
from django.urls import path
from . import views

app_name = 'accueil'

urlpatterns = [
    path('', views.index, name='index'),
]

projet_restaurant/authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
]

projet_restaurant/gestion_menus_plats/urls.py
from django.urls import path
from . import views

app_name = 'gestion_menus_plats'

urlpatterns = [
    path('plats/', views.plats, name='plats'),
    path('ajouter_plat/', views.ajouter_plat, name='ajouter_plat'),
]

projet_restaurant/livraison/urls.py
from django.urls import path
from . import views
app_name = 'livraison'
urlpatterns = [
    path('carte/', views.carte_livraison, name='carte_livraison'),
    path('ajouter/', views.ajouter_adresse, name='ajouter'),
    
]

projet_restaurant/reservation_en_ligne/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('reserver/', views.reserver, name='reserver'),
    path('ajouter_table',views.ajouter_table,name='ajouter_table'),
    path('reservations', views.reservations, name='reservations')
]

projet_restaurant/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Projet Restaurant{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block extra_css %}{% endblock %}
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<body>

<nav class="navbar navbar-expand-lg navbar-dark position-absolute w-100" style="top: 0; left: 0; z-index: 20; background: rgba(0,0,0,0.4);">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'accueil:index' %}">🍽️ Restaurant</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'accueil:index' %}">Accueil</a></li>
        {% if user.is_authenticated and user.is_client %}
          <li class="nav-item"><a class="nav-link" href="{% url 'reservation:reserver' %}">Réserver</a></li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'authentification:deconnexion' %}">Deconnexion</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'authentification:connexion' %}">Connexion</a></li>
        {% endif %}

        {% if user.is_authenticated and user.is_personnel %}
          <li class="nav-item"><a class="nav-link" href="{% url 'gestion_commande:commandes' %}">Gerer les commandes</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'reservation_en_ligne:reservations' %}">Gerer les reservations</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'gestion_menus_plats:ajouter_plat' %}">Ajouter Plat</a></li>
        {% endif %}

        <li class="nav-item"><a class="nav-link" href="{% url 'gestion_menus_plats:plats' %}">Menu</a></li>
        //<li class="nav-item"><a class="nav-link" href="{% url 'livraison:ajouter' %}">livraison</a></li>
      </ul>
    </div>
  </div>
</nav>
{% comment %} {% if messages %}
  <div class="container mt-3">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %} {% endcomment %}



{% block content %}{% endblock %}

<!-- Bootstrap JS -->

{% block extra_js %}{% endblock %}
</body>
</html>